name: Commit Linter

description: |
  GitHub Action that auto-installs commitlint configs/plugins, lints recent commits and posts a colored summary report.

author: mridang
branding:
  color: blue
  icon: box

inputs:
  github-token:
    description: >
      GitHub token used to authenticate API requests. Required for
      fetching commit information. Use `secrets.GITHUB_TOKEN` or a PAT
      with appropriate permissions.
    required: true

  commit-depth:
    description: >
      The maximum number of commits to lint from the push. If empty, all
      commits in the event will be linted.
    required: false

  allow-force-install:
    description: >
      If 'true', allows overwriting an existing package.json and forces
      npm to install dependencies using '--force' to resolve conflicting
      peer dependencies. Use with caution.
    required: false
    default: 'false'

  fail-on-warnings:
    description: >
      If 'true', the action will fail if any linting warnings are found.
      Defaults to 'false'.
    required: false
    default: 'false'

  fail-on-errors:
    description: >
      If 'false', the action will pass with a warning message even if
      linting errors are found. Defaults to 'true'.
    required: false
    default: 'true'

  help-url:
    description: >
      A URL to display in linting error messages, pointing users to your
      commit message guidelines.
    required: false

runs:
  using: node20
  main: dist/main.cjs
